sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - jruby-19mode
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 2.1.7
      jdk: openjdk7
    - rvm: 2.2.3
      jdk: openjdk7
  allow_failures:
    - rvm: jruby-head
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: openjdk7
notifications:
  email:
    - mflorisson@gmail.com
    - bruno@atnos.com
    - metienne@cityway.fr
    - zbouziane@cityway.fr
before_install:
  - gem update bundler
  - rm Gemfile.lock
before_script:
  - export JRUBY_OPTS="-J-XX:MaxPermSize=128m"
  - bundle exec rake ci:db_travis_config
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script: bundle exec rake spec
