language: ruby
rvm:
  - 1.8.7
  - ree
env:
  - DB=postgresql
before_script: 
  - "RAILS_ENV=test bundle exec rake ci:travis"
  - psql -c 'create database ninoxe_test;' -U postgres
script: "RAILS_ENV=test bundle exec rake ci:build"
notifications:
  recipients:
    - luc.donnet@dryade.net