language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-18mode
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
matrix:
  exclude: 
    - rvm:  1.8.7
      jdk: openjdk7
    - rvm:  1.8.7
      jdk: oraclejdk7
env:
  - DB=postgresql
before_script: 
  - "RAILS_ENV=test bundle exec rake ci:travis"
  - psql -c 'create database ninoxe_test;' -U postgres
script: "RAILS_ENV=test bundle exec rake ci:build"
notifications:
  recipients:
    - mflorisson@gmail.com
    - ldonnet@cityway.fr
    - metienne@cityway.fr
