development:
  adapter: postgresql
  database: ninoxe_dev
  username: chouette
  password: chouette
  schema_search_path: chouette
  
test:
  adapter: postgresql
  database: ninoxe_test
  username: chouette
  password: chouette
  schema_search_path: chouette

production:
  adapter: postgresql
  database: ninoxe_prod
  username: chouette
  password: chouette
  schema_search_path: chouette
